name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          # This makes the context of this action to be the merge commit itself
          # instead of the HEAD of the branch.
          # This is needed for the changeset action to be able to find the
          # changeset files.
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Dependencies
        run: pnpm install

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          # This will run `pnpm changeset publish` if a new version is released.
          publish: pnpm run release:npm
          commit: "chore: update package versions"
          title: "chore: update package versions"
        env:
          # The GITHUB_TOKEN is automatically generated by GitHub and is used by the
          # changesets action to create commits and pull requests.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # The NPM_TOKEN is a secret that you need to create in your repository settings.
          # It is used to authenticate with npm to publish the package.
          # 1. Generate a token at https://www.npmjs.com/settings/your-username/tokens
          # 2. Select "Granular Access Token". This is more secure.
          # 3. Give it "Read and Write" permissions for the specific `@infonomic/uikit` package.
          # 4. Add it to your GitHub repository secrets as NPM_TOKEN
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}